/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/common/app-provider.vue')['default']
    BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
    ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
    CountTo: typeof import('./../components/custom/count-to.vue')['default']
    DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
    DictSelect: typeof import('./../components/custom/dict-select.vue')['default']
    DictTag: typeof import('./../components/custom/dict-tag.vue')['default']
    DictText: typeof import('./../components/custom/dict-text.vue')['default']
    ExceptionBase: typeof import('./../components/common/exception-base.vue')['default']
    FullScreen: typeof import('./../components/common/full-screen.vue')['default']
    IconTooltip: typeof import('./../components/common/icon-tooltip.vue')['default']
    LangSwitch: typeof import('./../components/common/lang-switch.vue')['default']
    LookForward: typeof import('./../components/custom/look-forward.vue')['default']
    MenuToggler: typeof import('./../components/common/menu-toggler.vue')['default']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NWatermark: typeof import('naive-ui')['NWatermark']
    PinToggler: typeof import('./../components/common/pin-toggler.vue')['default']
    ReloadButton: typeof import('./../components/common/reload-button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderCaptcha: typeof import('./../components/custom/slider-captcha.vue')['default']
    SoybeanAvatar: typeof import('./../components/custom/soybean-avatar.vue')['default']
    SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
    SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
    TableColumnSetting: typeof import('./../components/advanced/table-column-setting.vue')['default']
    TableHeaderOperation: typeof import('./../components/advanced/table-header-operation.vue')['default']
    ThemeSchemaSwitch: typeof import('./../components/common/theme-schema-switch.vue')['default']
    WaveBg: typeof import('./../components/custom/wave-bg.vue')['default']
  }
}

// For TSX support
declare global {
  const AppProvider: typeof import('./../components/common/app-provider.vue')['default']
  const BetterScroll: typeof import('./../components/custom/better-scroll.vue')['default']
  const ButtonIcon: typeof import('./../components/custom/button-icon.vue')['default']
  const CountTo: typeof import('./../components/custom/count-to.vue')['default']
  const DarkModeContainer: typeof import('./../components/common/dark-mode-container.vue')['default']
  const DictSelect: typeof import('./../components/custom/dict-select.vue')['default']
  const DictTag: typeof import('./../components/custom/dict-tag.vue')['default']
  const DictText: typeof import('./../components/custom/dict-text.vue')['default']
  const ExceptionBase: typeof import('./../components/common/exception-base.vue')['default']
  const FullScreen: typeof import('./../components/common/full-screen.vue')['default']
  const IconTooltip: typeof import('./../components/common/icon-tooltip.vue')['default']
  const LangSwitch: typeof import('./../components/common/lang-switch.vue')['default']
  const LookForward: typeof import('./../components/custom/look-forward.vue')['default']
  const MenuToggler: typeof import('./../components/common/menu-toggler.vue')['default']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NWatermark: typeof import('naive-ui')['NWatermark']
  const PinToggler: typeof import('./../components/common/pin-toggler.vue')['default']
  const ReloadButton: typeof import('./../components/common/reload-button.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SliderCaptcha: typeof import('./../components/custom/slider-captcha.vue')['default']
  const SoybeanAvatar: typeof import('./../components/custom/soybean-avatar.vue')['default']
  const SvgIcon: typeof import('./../components/custom/svg-icon.vue')['default']
  const SystemLogo: typeof import('./../components/common/system-logo.vue')['default']
  const TableColumnSetting: typeof import('./../components/advanced/table-column-setting.vue')['default']
  const TableHeaderOperation: typeof import('./../components/advanced/table-header-operation.vue')['default']
  const ThemeSchemaSwitch: typeof import('./../components/common/theme-schema-switch.vue')['default']
  const WaveBg: typeof import('./../components/custom/wave-bg.vue')['default']
}