"""seed initial data

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-04

合并自历史 0002~0011 的全部种子数据（管理员/角色/菜单/字典/配置/定时任务，
以及商户管理、开放API日志、demo_openapi-test 等菜单的终态）。仅含 DML，
建表结构见 0001_initial_schema。
"""
from typing import Sequence, Union
from datetime import datetime

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ================================================================
# sys_config
# ================================================================

SYS_CONFIG_DATA = [
    {
        'id': 2,
        'key': 'rate_limit.enabled',
        'value': 'true',
        'default_value': 'true',
        'validation_rule': None,
        'description': '限流总开关',
        'type': 'BOOLEAN',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 3,
        'key': 'rate_limit.ip_per_minute',
        'value': '120',
        'default_value': '120',
        'validation_rule': None,
        'description': 'IP 全局限流（次/分钟）',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 4,
        'key': 'rate_limit.user_per_minute',
        'value': '300',
        'default_value': '300',
        'validation_rule': None,
        'description': '用户限流（次/分钟）',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 5,
        'key': 'rate_limit.login_fail_max',
        'value': '5',
        'default_value': '5',
        'validation_rule': None,
        'description': '登录失败上限次数',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 6,
        'key': 'rate_limit.login_fail_window',
        'value': '600',
        'default_value': '600',
        'validation_rule': None,
        'description': '登录失败统计窗口（秒）',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 7,
        'key': 'rate_limit.login_fail_block_ttl',
        'value': '1800',
        'default_value': '1800',
        'validation_rule': None,
        'description': '登录失败自动拉黑时长（秒）',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 8,
        'key': 'rate_limit.blacklist_redis_ttl',
        'value': '86400',
        'default_value': '86400',
        'validation_rule': None,
        'description': '永久黑名单 Redis 兜底 TTL（秒）',
        'type': 'NUMBER',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 9,
        'key': 'rate_limit.whitelist_path_prefixes',
        'value': '["/docs","/redoc","/openapi.json","/admin/health"]',
        'default_value': '["/docs","/redoc","/openapi.json","/admin/health"]',
        'validation_rule': None,
        'description': '路径白名单前缀',
        'type': 'JSON',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 10,
        'key': 'rate_limit.whitelist_ips',
        'value': '[]',
        'default_value': '[]',
        'validation_rule': None,
        'description': 'IP 白名单',
        'type': 'JSON',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 11,
        'key': 'rate_limit.path_rules',
        'value': '[]',
        'default_value': '[]',
        'validation_rule': None,
        'description': '路径细粒度限流规则',
        'type': 'JSON',
        'group': 'SECURITY',
        'is_system': True,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
]

# ================================================================
# sys_dict + sys_dict_item
# ================================================================

SYS_DICT_DATA = [
    {
        'id': 8,
        'name': '性别',
        'code': 'gender',
        'description': '性别字典：男、女、未知',
        'status': True,
        'is_system': True,
        'sort': 1,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 21, 52, 40),
        'updated_at': datetime(2026, 6, 3, 21, 52, 40),
    },
]

SYS_DICT_ITEM_DATA = [
    {
        'id': 7,
        'dict_id': 8,
        'value': '1',
        'label': '男',
        'description': None,
        'ext_info': None,
        'status': True,
        'sort': 1,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 21, 52, 40),
        'updated_at': datetime(2026, 6, 3, 21, 52, 40),
    },
    {
        'id': 8,
        'dict_id': 8,
        'value': '2',
        'label': '女',
        'description': None,
        'ext_info': None,
        'status': True,
        'sort': 2,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 21, 52, 40),
        'updated_at': datetime(2026, 6, 3, 21, 52, 40),
    },
    {
        'id': 9,
        'dict_id': 8,
        'value': '0',
        'label': '未知',
        'description': None,
        'ext_info': None,
        'status': True,
        'sort': 3,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 21, 52, 40),
        'updated_at': datetime(2026, 6, 3, 21, 52, 40),
    },
]

# ================================================================
# sys_user
# ================================================================

ADMIN_USER_ID = 2250298479026176

SYS_USER_DATA = [
    {
        'id': ADMIN_USER_ID,
        'username': 'admin',
        'password': '$2b$12$MPXWjrezSywnujoarubtJuKUJKBXugHEEqobTbIWtbJRXAp2aaTUy',
        'nickname': '超级管理员',
        'email': 'admin@example.com',
        'phone': '13800138000',
        'avatar': '',
        'last_login_at': None,
        'last_login_ip': '',
        'status': True,
        'is_superuser': True,
        'deleted_at': None,
        'created_at': datetime(2026, 2, 2, 10, 0, 29),
        'updated_at': datetime(2026, 2, 2, 10, 0, 29),
        'last_tenant_id': None,
    },
]

# ================================================================
# sys_role
# ================================================================

ADMIN_ROLE_ID = 2874692539129900

SYS_ROLE_DATA = [
    {
        'id': ADMIN_ROLE_ID,
        'name': '管理员',
        'status': True,
        'is_default': True,
        'is_system': True,
        'sort': 0,
        'deleted_at': None,
        'created_at': datetime(2026, 1, 1, 0, 0, 0),
        'updated_at': None,
        'desc': '系统默认管理员角色，拥有所有菜单权限',
    },
]

# ================================================================
# sys_menu
# ================================================================

SYS_MENU_DATA = [
    {
        'id': 2874692539129856,
        'parent_id': None,
        'name': 'home',
        'path': '/home',
        'component': 'layout.base$view.home',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:monitor-dashboard',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2907499345027073,
        'parent_id': None,
        'name': 'monitor',
        'path': '/monitor',
        'component': 'layout.base$view.monitor',
        'redirect': None,
        'permission': 'sys:monitor:list',
        'meta_icon': 'mdi:chart-areaspline-variant',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129857,
        'parent_id': None,
        'name': 'manage',
        'path': '/manage',
        'component': 'layout.base',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:cog',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'CATALOG',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': datetime(2026, 5, 29, 18, 23, 19),
    },
    {
        'id': 2874692539129858,
        'parent_id': None,
        'name': 'log',
        'path': '/log',
        'component': 'layout.base',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:file-document-outline',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'CATALOG',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': datetime(2026, 5, 29, 18, 23, 23),
    },
    {
        'id': 2907499345027072,
        'parent_id': None,
        'name': 'demo',
        'path': '/demo',
        'component': 'layout.base',
        'redirect': None,
        'permission': None,
        'meta_icon': 'arcticons:example',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'CATALOG',
        'sort': 5,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': datetime(2026, 5, 29, 15, 14, 30),
    },
    {
        'id': 2942406613671936,
        'parent_id': None,
        'name': 'scheduler',
        'path': '/scheduler',
        'component': 'layout.base',
        'redirect': '/scheduler/task',
        'permission': None,
        'meta_icon': 'material-symbols:schedule-outline',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'CATALOG',
        'sort': 95,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    # --- manage 子菜单 ---
    {
        'id': 2874692539129859,
        'parent_id': 2874692539129857,
        'name': 'manage_config',
        'path': '/manage/config',
        'component': 'view.manage_config',
        'redirect': None,
        'permission': 'sys:config:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129860,
        'parent_id': 2874692539129857,
        'name': 'manage_dict',
        'path': '/manage/dict',
        'component': 'view.manage_dict',
        'redirect': None,
        'permission': 'sys:dict:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129861,
        'parent_id': 2874692539129857,
        'name': 'manage_menu',
        'path': '/manage/menu',
        'component': 'view.manage_menu',
        'redirect': None,
        'permission': 'sys:menu:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129862,
        'parent_id': 2874692539129857,
        'name': 'manage_role',
        'path': '/manage/role',
        'component': 'view.manage_role',
        'redirect': None,
        'permission': 'sys:role:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129863,
        'parent_id': 2874692539129857,
        'name': 'manage_user',
        'path': '/manage/user',
        'component': 'view.manage_user',
        'redirect': None,
        'permission': 'sys:user:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 5,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2942406616000001,
        'parent_id': 2874692539129857,
        'name': 'manage_dept',
        'path': '/manage/dept',
        'component': 'view.manage_dept',
        'redirect': None,
        'permission': 'sys:dept:list',
        'meta_icon': 'ic:outline-account-tree',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 6,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 27, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000002,
        'parent_id': 2942406616000001,
        'name': 'manage_dept_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dept:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 27, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000003,
        'parent_id': 2942406616000001,
        'name': 'manage_dept_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dept:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 27, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000004,
        'parent_id': 2942406616000001,
        'name': 'manage_dept_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dept:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 27, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000005,
        'parent_id': 2942406616000001,
        'name': 'manage_dept_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dept:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 27, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2879249581154304,
        'parent_id': 2874692539129857,
        'name': 'log_online-user',
        'path': '/log/online-user',
        'component': 'view.log_online-user',
        'redirect': None,
        'permission': 'sys:online-user:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 9,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 11, 51, 1),
        'updated_at': datetime(2026, 5, 24, 14, 6, 39),
    },
    {
        'id': 2880487316791296,
        'parent_id': 2874692539129857,
        'name': 'manage_ip-blacklist',
        'path': '/manage/ip-blacklist',
        'component': 'view.manage_ip-blacklist',
        'redirect': None,
        'permission': 'sys:blacklist:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 10,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 2907499345027076,
        'parent_id': 2874692539129857,
        'name': 'manage_file',
        'path': '/manage/file',
        'component': 'view.manage_file',
        'redirect': None,
        'permission': 'sys:file:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 8,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': None,
    },
    {
        'id': 2886339278741504,
        'parent_id': 2874692539129857,
        'name': 'manage_announcement',
        'path': '/manage/announcement',
        'component': 'view.manage_announcement',
        'redirect': None,
        'permission': 'sys:notice:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 11,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    # --- log 子菜单 ---
    {
        'id': 2874692539129864,
        'parent_id': 2874692539129858,
        'name': 'log_login-log',
        'path': '/log/login-log',
        'component': 'view.log_login-log',
        'redirect': None,
        'permission': 'sys:login-log:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': None,
    },
    {
        'id': 2874692539129865,
        'parent_id': 2874692539129858,
        'name': 'log_operation-log',
        'path': '/log/operation-log',
        'component': 'view.log_operation-log',
        'redirect': None,
        'permission': 'sys:operation-log:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 23, 16, 32, 7),
        'updated_at': datetime(2026, 5, 24, 14, 6, 24),
    },
    # --- demo 子菜单 ---
    {
        'id': 2907499345027075,
        'parent_id': 2907499345027072,
        'name': 'demo_upload',
        'path': '/demo/upload',
        'component': 'view.demo_upload',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:upload',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 5,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': datetime(2026, 5, 29, 15, 13, 41),
    },
    {
        'id': 2907499345027081,
        'parent_id': 2907499345027072,
        'name': 'demo_dict',
        'path': '/demo/dict',
        'component': 'view.demo_dict',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:book-alphabet',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 16, 0, 0),
        'updated_at': None,
    },
    # --- scheduler 子菜单 ---
    {
        'id': 2942406615113728,
        'parent_id': 2942406613671936,
        'name': 'scheduler_task',
        'path': '/scheduler/task',
        'component': 'view.scheduler_task',
        'redirect': None,
        'permission': 'sys:scheduler:list',
        'meta_icon': 'material-symbols:task-alt-outline',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 1,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965702,
        'parent_id': 2942406613671936,
        'name': 'scheduler_log',
        'path': '/scheduler/log',
        'component': 'view.scheduler_log',
        'redirect': None,
        'permission': 'sys:scheduler:log:list',
        'meta_icon': 'material-symbols:history',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 2,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    # --- BUTTON 权限 ---
    {
        'id': 2907499345027074,
        'parent_id': 2907499345027073,
        'name': 'monitor_view',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:monitor:view',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 20, 18, 46),
        'updated_at': None,
    },
    {
        'id': 2880160334618624,
        'parent_id': 2874692539129861,
        'name': 'manage_menu_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:menu:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334618625,
        'parent_id': 2874692539129861,
        'name': 'manage_menu_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:menu:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334684160,
        'parent_id': 2874692539129861,
        'name': 'manage_menu_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:menu:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334684161,
        'parent_id': 2874692539129861,
        'name': 'manage_menu_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:menu:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334684162,
        'parent_id': 2874692539129862,
        'name': 'manage_role_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:role:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749696,
        'parent_id': 2874692539129862,
        'name': 'manage_role_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:role:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749697,
        'parent_id': 2874692539129862,
        'name': 'manage_role_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:role:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749698,
        'parent_id': 2874692539129862,
        'name': 'manage_role_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:role:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749699,
        'parent_id': 2874692539129863,
        'name': 'manage_user_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:user:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749700,
        'parent_id': 2874692539129863,
        'name': 'manage_user_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:user:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749701,
        'parent_id': 2874692539129863,
        'name': 'manage_user_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:user:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334749702,
        'parent_id': 2874692539129863,
        'name': 'manage_user_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:user:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334815232,
        'parent_id': 2874692539129860,
        'name': 'manage_dict_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dict:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334815233,
        'parent_id': 2874692539129860,
        'name': 'manage_dict_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dict:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334815234,
        'parent_id': 2874692539129860,
        'name': 'manage_dict_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dict:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334815235,
        'parent_id': 2874692539129860,
        'name': 'manage_dict_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:dict:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334815236,
        'parent_id': 2874692539129859,
        'name': 'manage_config_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:config:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880768,
        'parent_id': 2874692539129859,
        'name': 'manage_config_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:config:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880769,
        'parent_id': 2874692539129859,
        'name': 'manage_config_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:config:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880770,
        'parent_id': 2874692539129859,
        'name': 'manage_config_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:config:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880771,
        'parent_id': 2874692539129864,
        'name': 'log_login-log_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:log:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880772,
        'parent_id': 2874692539129864,
        'name': 'log_login-log_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:log:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334880773,
        'parent_id': 2874692539129865,
        'name': 'log_operation-log_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:oplog:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334946304,
        'parent_id': 2874692539129865,
        'name': 'log_operation-log_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:oplog:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334946305,
        'parent_id': 2879249581154304,
        'name': 'log_online-user_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:online:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880160334946306,
        'parent_id': 2879249581154304,
        'name': 'log_online-user_kick',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:online:kick',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 15, 42, 39),
        'updated_at': None,
    },
    {
        'id': 2880487316987904,
        'parent_id': 2880487316791296,
        'name': 'manage_ip-blacklist_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:blacklist:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 2880487317118976,
        'parent_id': 2880487316791296,
        'name': 'manage_ip-blacklist_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:blacklist:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 2880487317118977,
        'parent_id': 2880487316791296,
        'name': 'manage_ip-blacklist_remove',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:blacklist:remove',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 24, 17, 5, 48),
        'updated_at': None,
    },
    {
        'id': 2886339279134720,
        'parent_id': 2886339278741504,
        'name': 'manage_announcement_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:notice:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    {
        'id': 2886339279134721,
        'parent_id': 2886339278741504,
        'name': 'manage_announcement_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:notice:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    {
        'id': 2886339279134722,
        'parent_id': 2886339278741504,
        'name': 'manage_announcement_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:notice:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    {
        'id': 2886339279134723,
        'parent_id': 2886339278741504,
        'name': 'manage_announcement_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:notice:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    {
        'id': 2886339279134724,
        'parent_id': 2886339278741504,
        'name': 'manage_announcement_publish',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:notice:publish',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 5,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 25, 17, 54, 2),
        'updated_at': None,
    },
    {
        'id': 2907499345027077,
        'parent_id': 2907499345027076,
        'name': 'manage_file_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:file:list',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': None,
    },
    {
        'id': 2907499345027078,
        'parent_id': 2907499345027076,
        'name': 'manage_file_upload',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:file:upload',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': None,
    },
    {
        'id': 2907499345027079,
        'parent_id': 2907499345027076,
        'name': 'manage_file_download',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:file:download',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': None,
    },
    {
        'id': 2907499345027080,
        'parent_id': 2907499345027076,
        'name': 'manage_file_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:file:delete',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 5, 28, 23, 8, 7),
        'updated_at': None,
    },
    # --- scheduler buttons ---
    {
        'id': 2942406615965696,
        'parent_id': 2942406615113728,
        'name': '新增任务',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:add',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965697,
        'parent_id': 2942406615113728,
        'name': '编辑任务',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:edit',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965698,
        'parent_id': 2942406615113728,
        'name': '删除任务',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:delete',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965699,
        'parent_id': 2942406615113728,
        'name': '任务详情',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:detail',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965700,
        'parent_id': 2942406615113728,
        'name': '启停任务',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:status',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406615965701,
        'parent_id': 2942406615113728,
        'name': '手动执行',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:trigger',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406617800704,
        'parent_id': 2942406615965702,
        'name': '日志详情',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:log:detail',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    {
        'id': 2942406617800705,
        'parent_id': 2942406615965702,
        'name': '删除日志',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:scheduler:log:delete',
        'meta_icon': None,
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 0,
        'is_system': False,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 32, 41),
        'updated_at': None,
    },
    # --- merchant-open 目录、商户管理、开放API日志（合并自历史 0008/0009）---
    # manage_merchant 最终归入 merchant-open 目录（0009 迁移后的终态）
    {
        'id': 2942406616000020,
        'parent_id': None,
        'name': 'merchant-open',
        'path': '/merchant-open',
        'component': 'layout.base',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:connection',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'CATALOG',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 5, 12, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000010,
        'parent_id': 2942406616000020,
        'name': 'merchant-open_merchant',
        'path': '/merchant-open/merchant',
        'component': 'view.merchant-open_merchant',
        'redirect': None,
        'permission': 'sys:merchant:list',
        'meta_icon': 'mdi:store',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000011,
        'parent_id': 2942406616000010,
        'name': 'manage_merchant_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:merchant:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000012,
        'parent_id': 2942406616000010,
        'name': 'manage_merchant_add',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:merchant:add',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000013,
        'parent_id': 2942406616000010,
        'name': 'manage_merchant_edit',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:merchant:edit',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000014,
        'parent_id': 2942406616000010,
        'name': 'manage_merchant_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:merchant:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 4,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000015,
        'parent_id': 2942406616000010,
        'name': 'manage_merchant_reset_secret',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:merchant:reset-secret',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 5,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 4, 10, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000021,
        'parent_id': 2942406616000020,
        'name': 'merchant-open_openapi-log',
        'path': '/merchant-open/openapi-log',
        'component': 'view.merchant-open_openapi-log',
        'redirect': None,
        'permission': 'sys:openapi-log:list',
        'meta_icon': 'mdi:chart-line-variant',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 5, 12, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000022,
        'parent_id': 2942406616000021,
        'name': 'merchant-open_openapi-log_list',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:openapi-log:list',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 1,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 5, 12, 0, 0),
        'updated_at': None,
    },
    {
        'id': 2942406616000023,
        'parent_id': 2942406616000021,
        'name': 'merchant-open_openapi-log_delete',
        'path': None,
        'component': None,
        'redirect': None,
        'permission': 'sys:openapi-log:delete',
        'meta_icon': None,
        'meta_hidden': True,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'BUTTON',
        'sort': 2,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 5, 12, 0, 0),
        'updated_at': None,
    },
    # --- demo_openapi-test 菜单（合并自历史 0010）---
    {
        'id': 2942406616000030,
        'parent_id': 2907499345027072,
        'name': 'demo_openapi-test',
        'path': '/demo/openapi-test',
        'component': 'view.demo_openapi-test',
        'redirect': None,
        'permission': None,
        'meta_icon': 'mdi:link-variant',
        'meta_hidden': False,
        'meta_affix': False,
        'meta_breadcrumb': True,
        'status': True,
        'type': 'MENU',
        'sort': 3,
        'is_system': True,
        'meta_href': None,
        'meta_keep_alive': False,
        'deleted_at': None,
        'created_at': datetime(2026, 7, 5, 14, 0, 0),
        'updated_at': None,
    },
]

# ================================================================
# sys_role_menu (管理员 -> 所有菜单)
# ================================================================

_ALL_MENU_IDS = [row['id'] for row in SYS_MENU_DATA]

SYS_ROLE_MENU_DATA = [
    {
        'role_id': ADMIN_ROLE_ID,
        'menu_id': mid,
        'permission': 'read',
    }
    for mid in _ALL_MENU_IDS
]

# ================================================================
# sys_user_role (admin -> 管理员)
# ================================================================

SYS_USER_ROLE_DATA = [
    {
        'user_id': ADMIN_USER_ID,
        'role_id': ADMIN_ROLE_ID,
    },
]

# ================================================================
# sys_scheduled_task
# ================================================================

SYS_SCHEDULED_TASK_DATA = [
    {
        'id': 2938394705010688,
        'name': '清理过期操作日志',
        'task_key': 'system.cleanup_operation_logs',
        'cron_expression': '0 3 * * *',
        'description': '自动清理30天前的操作日志',
        'trigger_type': 'cron',
        'trigger_params': None,
        'status': True,
        'module': 'modules.scheduler.tasks.builtin',
        'function_path': 'modules.scheduler.tasks.builtin.cleanup_operation_logs',
        'is_system': True,
        'last_run_at': None,
        'next_run_at': None,
        'last_status': None,
        'timeout': 300,
        'max_retries': 0,
        'concurrent_policy': 'skip',
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 22, 32, 24),
        'updated_at': None,
    },
    {
        'id': 2938394705010689,
        'name': '清理过期登录日志',
        'task_key': 'system.cleanup_login_logs',
        'cron_expression': '0 4 * * *',
        'description': '自动清理30天前的登录日志',
        'trigger_type': 'cron',
        'trigger_params': None,
        'status': True,
        'module': 'modules.scheduler.tasks.builtin',
        'function_path': 'modules.scheduler.tasks.builtin.cleanup_login_logs',
        'is_system': True,
        'last_run_at': None,
        'next_run_at': None,
        'last_status': None,
        'timeout': 300,
        'max_retries': 0,
        'concurrent_policy': 'skip',
        'deleted_at': None,
        'created_at': datetime(2026, 6, 3, 22, 32, 24),
        'updated_at': None,
    },
    {
        'id': 2942449943060480,
        'name': '刷新限流配置缓存',
        'task_key': 'system.refresh_rate_limit_config',
        'cron_expression': '25',
        'description': '定时从数据库刷新限流参数到内存缓存，避免请求路径上回源',
        'trigger_type': 'interval',
        'trigger_params': '{"seconds": 25}',
        'status': True,
        'module': 'modules.scheduler.tasks.rate_limit_config',
        'function_path': 'modules.scheduler.tasks.rate_limit_config.refresh_rate_limit_config',
        'is_system': True,
        'last_run_at': None,
        'next_run_at': None,
        'last_status': None,
        'timeout': 300,
        'max_retries': 0,
        'concurrent_policy': 'skip',
        'deleted_at': None,
        'created_at': datetime(2026, 6, 4, 15, 43, 43),
        'updated_at': None,
    },
]


def upgrade() -> None:
    op.bulk_insert(
        sa.table(
            'sys_config',
            sa.column('id', sa.Integer),
            sa.column('key', sa.String),
            sa.column('value', sa.String),
            sa.column('default_value', sa.String),
            sa.column('validation_rule', sa.String),
            sa.column('description', sa.String),
            sa.column('type', sa.String),
            sa.column('group', sa.String),
            sa.column('is_system', sa.Boolean),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        SYS_CONFIG_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_dict',
            sa.column('id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('description', sa.String),
            sa.column('status', sa.Boolean),
            sa.column('is_system', sa.Boolean),
            sa.column('sort', sa.Integer),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        SYS_DICT_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_user',
            sa.column('id', sa.BigInteger),
            sa.column('username', sa.String),
            sa.column('password', sa.String),
            sa.column('nickname', sa.String),
            sa.column('email', sa.String),
            sa.column('phone', sa.String),
            sa.column('avatar', sa.String),
            sa.column('last_login_at', sa.DateTime),
            sa.column('last_login_ip', sa.String),
            sa.column('status', sa.Boolean),
            sa.column('is_superuser', sa.Boolean),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
            sa.column('last_tenant_id', sa.BigInteger),
        ),
        SYS_USER_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_role',
            sa.column('id', sa.BigInteger),
            sa.column('name', sa.String),
            sa.column('status', sa.Boolean),
            sa.column('is_default', sa.Boolean),
            sa.column('is_system', sa.Boolean),
            sa.column('sort', sa.Integer),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
            sa.column('desc', sa.String),
        ),
        SYS_ROLE_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_menu',
            sa.column('id', sa.BigInteger),
            sa.column('parent_id', sa.BigInteger),
            sa.column('name', sa.String),
            sa.column('path', sa.String),
            sa.column('component', sa.String),
            sa.column('redirect', sa.String),
            sa.column('permission', sa.String),
            sa.column('meta_icon', sa.String),
            sa.column('meta_hidden', sa.Boolean),
            sa.column('meta_affix', sa.Boolean),
            sa.column('meta_breadcrumb', sa.Boolean),
            sa.column('status', sa.Boolean),
            sa.column('type', sa.String),
            sa.column('sort', sa.Integer),
            sa.column('is_system', sa.Boolean),
            sa.column('meta_href', sa.String),
            sa.column('meta_keep_alive', sa.Boolean),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        SYS_MENU_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_dict_item',
            sa.column('id', sa.Integer),
            sa.column('dict_id', sa.Integer),
            sa.column('value', sa.String),
            sa.column('label', sa.String),
            sa.column('description', sa.String),
            sa.column('ext_info', sa.String),
            sa.column('status', sa.Boolean),
            sa.column('sort', sa.Integer),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        SYS_DICT_ITEM_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_role_menu',
            sa.column('role_id', sa.BigInteger),
            sa.column('menu_id', sa.BigInteger),
            sa.column('permission', sa.String),
        ),
        SYS_ROLE_MENU_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_user_role',
            sa.column('user_id', sa.BigInteger),
            sa.column('role_id', sa.BigInteger),
        ),
        SYS_USER_ROLE_DATA,
    )

    op.bulk_insert(
        sa.table(
            'sys_scheduled_task',
            sa.column('id', sa.BigInteger),
            sa.column('name', sa.String),
            sa.column('task_key', sa.String),
            sa.column('cron_expression', sa.String),
            sa.column('description', sa.String),
            sa.column('trigger_type', sa.String),
            sa.column('trigger_params', sa.String),
            sa.column('status', sa.Boolean),
            sa.column('module', sa.String),
            sa.column('function_path', sa.String),
            sa.column('is_system', sa.Boolean),
            sa.column('last_run_at', sa.DateTime),
            sa.column('next_run_at', sa.DateTime),
            sa.column('last_status', sa.String),
            sa.column('timeout', sa.Integer),
            sa.column('max_retries', sa.Integer),
            sa.column('concurrent_policy', sa.String),
            sa.column('deleted_at', sa.DateTime),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime),
        ),
        SYS_SCHEDULED_TASK_DATA,
    )


def downgrade() -> None:
    op.execute('DELETE FROM sys_user_role')
    op.execute('DELETE FROM sys_role_menu')
    op.execute('DELETE FROM sys_dict_item')
    op.execute('DELETE FROM sys_scheduled_task')
    op.execute('DELETE FROM sys_user')
    op.execute('DELETE FROM sys_role')
    op.execute('DELETE FROM sys_menu')
    op.execute('DELETE FROM sys_dict')
    op.execute('DELETE FROM sys_config')
