"""add agent module tables

Revision ID: d2d73eede47a
Revises: 0004
Create Date: 2026-10-02 17:40:09.610609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2d73eede47a'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_agent',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='智能体名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='智能体编码'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='绑定模型 ID（sys_agent_model.id，逻辑引用）'),
    sa.Column('system_prompt', sa.Text(), nullable=True, comment='系统提示词'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='温度（0-2，0=未设置）'),
    sa.Column('top_p', sa.Float(), nullable=False, comment='Top-P（0-1，0=未设置）'),
    sa.Column('max_tokens', sa.Integer(), nullable=False, comment='单次最大输出（token，0=上游默认）'),
    sa.Column('tools', sa.String(length=512), nullable=True, comment='绑定的工具名 JSON 数组文本'),
    sa.Column('skills', sa.String(length=512), nullable=True, comment='绑定的技能编码 JSON 数组文本'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uk_sys_agent_code')
    )
    op.create_index(op.f('ix_sys_agent_code'), 'sys_agent', ['code'], unique=False)
    op.create_index(op.f('ix_sys_agent_id'), 'sys_agent', ['id'], unique=True)
    op.create_index('ix_sys_agent_model_ref', 'sys_agent', ['model_id'], unique=False)
    op.create_table('sys_agent_conversation',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='归属用户 ID'),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='关联智能体 ID（逻辑引用，不级联）'),
    sa.Column('agent_name', sa.String(length=20), nullable=False, comment='智能体名称冗余（Agent 删除后历史可读）'),
    sa.Column('title', sa.String(length=64), nullable=False, comment='会话标题'),
    sa.Column('last_msg_at', sa.DateTime(timezone=True), nullable=True, comment='最近消息时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    智能体会话表\n    归属用户本人；agent_name 冗余存储，Agent 删除后历史仍可读\n    '
    )
    op.create_index(op.f('ix_sys_agent_conversation_agent_id'), 'sys_agent_conversation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sys_agent_conversation_id'), 'sys_agent_conversation', ['id'], unique=True)
    op.create_index(op.f('ix_sys_agent_conversation_user_id'), 'sys_agent_conversation', ['user_id'], unique=False)
    op.create_table('sys_agent_conversation_msg',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('conversation_id', sa.Integer(), nullable=False, comment='所属会话 ID（sys_agent_conversation.id）'),
    sa.Column('role', sa.String(length=16), nullable=False, comment='消息角色：user/assistant'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='assistant 消息的 usage.total_tokens'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    会话消息表\n    追加流水；随会话物理删除，不提供单独修改\n    '
    )
    op.create_index(op.f('ix_sys_agent_conversation_msg_conversation_id'), 'sys_agent_conversation_msg', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_sys_agent_conversation_msg_id'), 'sys_agent_conversation_msg', ['id'], unique=True)
    op.create_table('sys_agent_model',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='所属供应商 ID（sys_agent_provider.id）'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='模型名称（上游模型 ID）'),
    sa.Column('display_name', sa.String(length=64), nullable=True, comment='展示名称'),
    sa.Column('context_window', sa.Integer(), nullable=False, comment='上下文窗口（token，0=未知）'),
    sa.Column('max_output', sa.Integer(), nullable=False, comment='单次最大输出（token，0=上游默认）'),
    sa.Column('supports_tools', sa.Boolean(), nullable=False, comment='是否支持工具调用'),
    sa.Column('input_price', sa.Float(), nullable=False, comment='每千 token 输入单价（0=未设置）'),
    sa.Column('output_price', sa.Float(), nullable=False, comment='每千 token 输出单价（0=未设置）'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'name', name='uk_sys_agent_model_provider_name')
    )
    op.create_index(op.f('ix_sys_agent_model_id'), 'sys_agent_model', ['id'], unique=True)
    op.create_index(op.f('ix_sys_agent_model_provider_id'), 'sys_agent_model', ['provider_id'], unique=False)
    op.create_table('sys_agent_provider',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='供应商名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='供应商编码'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='OpenAI 兼容 API 基础地址'),
    sa.Column('api_key_enc', sa.String(length=512), nullable=True, comment='API Key 密文（AES-256-GCM base64）'),
    sa.Column('api_key_mask', sa.String(length=32), nullable=True, comment='API Key 掩码（仅展示用）'),
    sa.Column('protocol', sa.String(length=32), nullable=False, comment='调用协议，预留多协议扩展'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uk_sys_agent_provider_code')
    )
    op.create_index(op.f('ix_sys_agent_provider_code'), 'sys_agent_provider', ['code'], unique=False)
    op.create_index(op.f('ix_sys_agent_provider_id'), 'sys_agent_provider', ['id'], unique=True)
    op.create_table('sys_agent_usage_log',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('agent_id', sa.Integer(), nullable=False, comment='智能体 ID'),
    sa.Column('model_id', sa.Integer(), nullable=False, comment='模型 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户 ID'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='输入 token 数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='输出 token 数'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='总 token 数'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='耗时（毫秒）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='\n    智能体 token 用量计量流水表\n    每次对话一条（含无状态调试）；按保留期由定时任务清理\n    '
    )
    op.create_index(op.f('ix_sys_agent_usage_log_agent_id'), 'sys_agent_usage_log', ['agent_id'], unique=False)
    op.create_index(op.f('ix_sys_agent_usage_log_id'), 'sys_agent_usage_log', ['id'], unique=True)
    op.create_index(op.f('ix_sys_agent_usage_log_user_id'), 'sys_agent_usage_log', ['user_id'], unique=False)
    op.create_table('sys_mcp_server',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='服务名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='服务编码（禁用冒号，供 mcp:<code>:<tool> 引用）'),
    sa.Column('base_url', sa.String(length=255), nullable=False, comment='消息端点地址（streamable_http）或事件流端点（sse）'),
    sa.Column('transport', sa.String(length=20), nullable=False, comment='传输协议：streamable_http / sse'),
    sa.Column('headers', sa.Text(), nullable=True, comment='自定义请求头 JSON 数组文本'),
    sa.Column('token_enc', sa.String(length=512), nullable=True, comment='鉴权 Token 密文（AES-256-GCM base64）'),
    sa.Column('token_mask', sa.String(length=32), nullable=True, comment='鉴权 Token 掩码（仅展示用）'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uk_sys_mcp_server_code')
    )
    op.create_index(op.f('ix_sys_mcp_server_code'), 'sys_mcp_server', ['code'], unique=False)
    op.create_index(op.f('ix_sys_mcp_server_id'), 'sys_mcp_server', ['id'], unique=True)
    op.create_table('sys_skill',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('name', sa.String(length=20), nullable=False, comment='技能名称'),
    sa.Column('code', sa.String(length=64), nullable=False, comment='技能编码'),
    sa.Column('instruction', sa.Text(), nullable=False, comment='主指令（Markdown 提示词）'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='技能描述'),
    sa.Column('remark', sa.String(length=200), nullable=True, comment='备注'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-禁用'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uk_sys_skill_code')
    )
    op.create_index(op.f('ix_sys_skill_code'), 'sys_skill', ['code'], unique=False)
    op.create_index(op.f('ix_sys_skill_id'), 'sys_skill', ['id'], unique=True)
    op.create_table('sys_skill_file',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='雪花算法主键 ID'),
    sa.Column('skill_id', sa.Integer(), nullable=False, comment='所属技能 ID（sys_skill.id）'),
    sa.Column('path', sa.String(length=128), nullable=False, comment='相对路径（禁绝对路径与 ..）'),
    sa.Column('content', sa.Text(), nullable=False, comment='文件文本内容'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='文件大小（字节）'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间，为空则未删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'path', name='uk_sys_skill_file_path')
    )
    op.create_index(op.f('ix_sys_skill_file_id'), 'sys_skill_file', ['id'], unique=True)
    op.create_index(op.f('ix_sys_skill_file_skill_id'), 'sys_skill_file', ['skill_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('sys_skill_file')
    op.drop_table('sys_skill')
    op.drop_table('sys_mcp_server')
    op.drop_table('sys_agent_usage_log')
    op.drop_table('sys_agent_provider')
    op.drop_table('sys_agent_model')
    op.drop_table('sys_agent_conversation_msg')
    op.drop_table('sys_agent_conversation')
    op.drop_table('sys_agent')
