/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  demo_dict: () => import("@/views/demo/dict/index.vue"),
  demo_upload: () => import("@/views/demo/upload/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "log_login-log": () => import("@/views/log/login-log/index.vue"),
  "log_online-user": () => import("@/views/log/online-user/index.vue"),
  "log_operation-log": () => import("@/views/log/operation-log/index.vue"),
  "log_robot-log": () => import("@/views/log/robot-log/index.vue"),
  manage_announcement: () => import("@/views/manage/announcement/index.vue"),
  manage_config: () => import("@/views/manage/config/index.vue"),
  manage_dict: () => import("@/views/manage/dict/index.vue"),
  manage_file: () => import("@/views/manage/file/index.vue"),
  "manage_ip-blacklist": () => import("@/views/manage/ip-blacklist/index.vue"),
  manage_menu: () => import("@/views/manage/menu/index.vue"),
  manage_role: () => import("@/views/manage/role/index.vue"),
  "manage_scheduler-log": () => import("@/views/manage/scheduler-log/index.vue"),
  manage_scheduler: () => import("@/views/manage/scheduler/index.vue"),
  manage_user: () => import("@/views/manage/user/index.vue"),
  monitor: () => import("@/views/monitor/index.vue"),
  "operation-monitor": () => import("@/views/operation-monitor/index.vue"),
  robot_manage: () => import("@/views/robot/manage/index.vue"),
  robot_model: () => import("@/views/robot/model/index.vue"),
  scene_group: () => import("@/views/scene/group/index.vue"),
  "scene_map-editor": () => import("@/views/scene/map-editor/index.vue"),
  scene_map: () => import("@/views/scene/map/index.vue"),
  settings: () => import("@/views/settings/index.vue"),
  task: () => import("@/views/task/index.vue"),
};
